name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug SSH Setup
      run: |
        echo "Key length: $(echo "${{ secrets.EC2_SSH_KEY }}" | wc -c)"
        echo "Host: ${{ secrets.EC2_HOST }}"
        echo "User: ec2-user"
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa | head -n 2

    - name: Set up SSH
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> /home/runner/.ssh/known_hosts


    - name: Pull latest code and restart app
      run: |
        ssh -i /home/runner/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /~/SI_Card_Bot
          git pull origin main
          pm2 restart index.js
        EOF

